#!/bin/bash -l
#
##############
# job script #
##############
#
#SBATCH --job-name=2Blades_0822
#SBATCH --nodes=1
#SBATCH --ntasks=21
#SBATCH --ntasks-per-node=21
#SBATCH --partition prandtl
#
#              d-hh:mm:ss
#SBATCH  --time=0-24:00:00
# 500MB memory per core
# this is a hard limit
##SBATCH --mem-per-cpu=500MB
#
# turn on all mail notification
#SBATCH --mail-user=st154876@stud.uni-stuttgart.de
#SBATCH --mail-type=ALL
#
# you may not place bash commands before the last SBATCH directive

# define and create a unique scratch directory
SCRATCH_DIRECTORY=/scratch/ws/ws1/iagschli-test_workspace/slurm_activities/${SLURM_JOBID}

mkdir -p ${SCRATCH_DIRECTORY}
mkdir -p ${SLURM_SUBMIT_DIR}/slurm_result
cd ${SCRATCH_DIRECTORY}

# copy submitted files to the scratch directory
cp -r ${SLURM_SUBMIT_DIR}/. ${SCRATCH_DIRECTORY}

#load necessary modules

module purge
module load gnu/8.3.0
module load openmpi3/3.1.6
module load py3-mpi4py/3.0.2
module load boost/1.71.0
source /opt/software/openfoam/openfoamv2012/OpenFOAM-v2012/etc/bashrc
export PYTHONPATH=$PYTHONPATH:/home/iagschli/software/mbdyn/libexec/mbpy
export LD_LIBRARY_PATH=/home/iagschli/software/petsc/arch-linux2-c-opt/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/iagschli/software/precice/lib64:$LD_LIBRARY_PATH

#python installer
#/usr/bin/python3 -m pip install --upgrade pip --user

#clean
rm -r openfoam/0.* openfoam/[1-9]* openfoam/postProcessing openfoam/processor* precice-run exchange*.sock

# execute the job
decomposePar -case openfoam |tee decomposePar.log
python3 solidSolver.py > python.log 2>&1 &
mpirun -np 20 overPimpleDyMFoam -case openfoam -parallel |tee overPimpleDyMFoam.log
#reconstructPar -case openfoam > reconstructPar.log
#rm -r openfoam/processor*
# after the job is done we copy our output back to $SLURM_SUBMIT_DIR
#cp -r ${SCRATCH_DIRECTORY} ${SLURM_SUBMIT_DIR}/slurm_result

# we step out of the scratch directory and remove it
#cd ${SLURM_SUBMIT_DIR}
#rm -rf ${SCRATCH_DIRECTORY}

# end
exit 0
